name='tim'
print('hello.\nmy name is balaji')
print(len(name))
print(name.index('i'))
print(name.upper().isupper())
print(name.islower())
print(name.replace('m','x'))
print(name[0])
print(name.upper())
print(name.lower())